---
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - bc
    - cmake
    - python-docutils
    - valgrind
install:
  - curl -s https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz | tar xz
script:
  - mkdir build
  - cd build
  - ../cmake-3.1.3-Linux-x86_64/bin/cmake -DMEMCHECK=ON ..
  - make check
after_failure:
  - cat tst/Testing/Temporary/LastTest.log
