---
language: c
compiler:
  - clang
  - gcc
env:
  - CMAKE_FLAGS=-DCMAKE_C_FLAGS=-O0
  - CMAKE_FLAGS=-DCMAKE_C_FLAGS=-O1
  - CMAKE_FLAGS=-DCMAKE_C_FLAGS=-O2
  - CMAKE_FLAGS=-DCMAKE_C_FLAGS=-O3
  - CMAKE_FLAGS=-DCMAKE_C_FLAGS=-Os
  - CMAKE_FLAGS=-DMEMCHECK=ON
  - CMAKE_FLAGS=-DCOVERAGE=ON
  - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Release
addons:
  apt:
    packages:
    - bc
    - cmake
    - python-docutils
    - valgrind
install:
  - curl -s https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz | tar xz
script:
  - mkdir build
  - cd build
  - ../cmake-3.1.3-Linux-x86_64/bin/cmake $CMAKE_FLAGS ..
  - make check
after_failure:
  - cat tst/Testing/Temporary/LastTest.log
