---
language: c
compiler:
  - clang
  - gcc
env:
  - CFLAGS=-O0
  - CFLAGS=-O1
  - CFLAGS=-O2
  - CFLAGS=-O3
  - CFLAGS=-Os
  - BUILD_FLAGS=--with-memcheck
  - BUILD_FLAGS=--with-lcov
matrix:
  include:
    - compiler: clang
      env: BUILD_FLAGS=--with-asan
    - compiler: clang
      env: BUILD_FLAGS=--with-ubsan
    - compiler: gcc
      env: CFLAGS=-m32
addons:
  apt:
    packages:
    - bc
    - gcc-multilib
    - lcov
    - python-docutils
    - valgrind
script:
  - mkdir build
  - cd build
  - ../bootstrap $BUILD_FLAGS
  - make check
after_failure:
  - cat tst/test-suite.log
