---
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - cmake
    - python-docutils
    - valgrind
install:
  - wget -qO- https://www.cmake.org/files/v3.0/cmake-3.0.2-Linux-x86_64.tar.gz | tar xvz
script:
  - set -e
  - mkdir build
  - cd build
  - ./cmake-3.0.2-Linux-x86_64/bin/cmake -DMEMCHECK=ON ..
  - make check
