---
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - cmake
    - python-docutils
    - valgrind
sudo: false
script:
  - set -e
  - mkdir build
  - cd build
  - cmake -DMEMCHECK=ON ..
  - make check
