#!/bin/sh

set -e
set -u

ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"

test "${LGTM_WORKSPACE:+set}" = set &&
sed -i '/CASHPACK_ARG_ENABLE..docs/d' configure.ac

autoreconf -i "$ROOT_DIR"

test "${LGTM_WORKSPACE:+set}" = set && exit

"$ROOT_DIR"/configure \
	--enable-docs \
	--enable-warnings \
	--enable-hardening \
	--enable-silent-rules \
	"$@"
