#!/bin/sh

set -e
set -u

WORK_DIR=$(pwd)
ROOT_DIR=$(dirname "$0")

test -n "$ROOT_DIR"
cd "$ROOT_DIR"

test "${LGTM_WORKSPACE:+set}" = set &&
sed -i '/CASHPACK_ARG_ENABLE..docs/d' configure.ac

if ! command -v libtoolize >/dev/null 2>&1
then
	echo 'libtoolize: command not found, falling back to glibtoolize' >&2
	alias libtoolize=glibtoolize
fi

aclocal -I m4
libtoolize --copy --force
automake --add-missing --copy --foreign
autoreconf

test "${LGTM_WORKSPACE:+set}" = set && exit

cd "$WORK_DIR"
"$ROOT_DIR"/configure \
	--enable-docs \
	--enable-warnings \
	--enable-hardening \
	--enable-silent-rules \
	"$@"
