#!/bin/sh
#
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.

set -e
set -u

project_dir="$(dirname "$0")"

[ $# == 0 ] &&
git_ref="$(git rev-parse --abbrev-ref HEAD)" ||
git_ref="$1"

dist_dir="$PWD"
dist_fmt="tar.gz"
dist_pfx="cashpack-${git_ref}/"
dist_out="${dist_dir}/cashpack-${git_ref}.${dist_fmt}"

cd ${project_dir}
git archive \
	--format="${dist_fmt}" \
	--output="${dist_out}" \
	--prefix="${dist_pfx}" \
	${git_ref}
