#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# Check that bindumps are succesfully turned into hexdumps.

. "$(dirname "$0")"/common.sh

cmd_check bc

hex="$TEST_TMP/hex"
dmp="$TEST_TMP/dmp"

cat >"$dmp" <<EOF
0011 2244 88f0 ff                       | .."D...
EOF

mk_bin <<EOF
00000000 | 0x00
00010001 | 0x11
00100010 | 0x22
01000100 | 0x44
10001000 | 0x88
11110000 | 0xf0 (a great game)
11111111 | 0xff
EOF

diff -u "$hex" "$dmp" >&2
