#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

_ -------------------------
_ Enlarge the dynamic table
_ -------------------------

mk_hex </dev/null
mk_msg </dev/null
mk_tbl </dev/null

mk_enc <<EOF
resize 9001
EOF

tst_encode
