#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

_ -----------------------------------------
_ A never-indexed field with a broken index
_ -----------------------------------------

mk_bin <<EOF
00011111 | a packed integer that expects a continuation
EOF

tst_decode --expect-error BUF

_ -----------------
_ Incomplete string
_ -----------------

mk_bin <<EOF
00000000 | a literal header field
00000001 | with a 1-character name
EOF

tst_decode --expect-error BUF
