#!/bin/sh
#
# Copyright (c) 2016 Dridi Boukelmoune
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

. "$(dirname "$0")"/common.sh

_ ----------------------------------------
_ Use the indexed name of an evicted field
_ ----------------------------------------

mk_hex <<EOF
4004 6e61 6d65 0576 616c 7565 7e06 7570 | @.name.value~.up
6461 7465                               | date
EOF

mk_tbl <<EOF
[  1] (s =  42) name: update
      Table size:  42
EOF

mk_enc <<EOF
dynamic str name str value
dynamic idx 62 str update
EOF

tst_encode --table-size 42

_ -------------------------------------------------------------
_ Use the indexed name of an evicted field in a non-empty table
_ -------------------------------------------------------------

mk_hex <<EOF
4004 6e61 6d65 0576 616c 7565 4005 6f74 | @.name.value@.ot
6865 7205 656e 7472 797f 0006 7570 6461 | her.entry...upda
7465                                    | te
EOF

mk_tbl <<EOF
[  1] (s =  42) name: update
[  2] (s =  42) other: entry
      Table size:  84
EOF

mk_enc <<EOF
dynamic str name str value
dynamic str other str entry
dynamic idx 63 str update
EOF

tst_encode --table-size 84

_ -------------------------
_ Enlarge the dynamic table
_ -------------------------

mk_hex </dev/null

mk_enc <<EOF
resize 9001
EOF

tst_encode
