#!/bin/sh
#
# Copyright (c) 2016 Dridi Boukelmoune
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

. "$(dirname "$0")"/common.sh

mk_msg </dev/null
mk_tbl </dev/null

# ================
# Buffer overflows
# ================

mk_bin <<EOF
11111111 | The rest of the integer is missing...
EOF

tst_decode --expect-error BUF

mk_bin <<EOF
00000000 | Try to read two integers with only one available
EOF

tst_decode --expect-error BUF

# =================
# Integer overflows
# =================

mk_bin <<EOF
11111111 | Use an indexed field
10000001 | to make a 7+ integer
11111111 | overflow with the
00000011 | value UINT16_MAX + 1
EOF

tst_decode --expect-error INT

mk_bin <<EOF
01111111 | Use a dynamic field
11000001 | to make a 6+ integer
11111111 | overflow with the
00000011 | value UINT16_MAX + 1
EOF

tst_decode --expect-error INT

mk_bin <<EOF
00111111 | Use a table update
11100001 | to make a 5+ integer
11111111 | overflow with the
00000011 | value UINT16_MAX + 1
EOF

tst_decode --expect-error INT

mk_bin <<EOF
00001111 | Use a literal field
11110001 | to make a 4+ integer
11111111 | overflow with the
00000011 | value UINT16_MAX + 1
EOF

tst_decode --expect-error INT

# =======
# Fuzzing
# =======

mk_bin <<EOF
00111111 | Use a table update
10000000 | to make a 5+ integer
10000000 | stupidly packed with
10000000 | way more bytes than
10000000 | needed to encode its
10000000 | rather small value.
00000000 | It must work regarless.
EOF

tst_decode --table-size 1024
