#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex </dev/null
mk_msg </dev/null
mk_tbl </dev/null

_ ----------
_ Null index
_ ----------

mk_enc <<EOF
indexed 0
EOF

tst_encode --expect-error IDX

_ ---------------
_ Index too large
_ ---------------

mk_enc <<EOF
indexed 99999
EOF

tst_encode --expect-error IDX

_ -------------------
_ Wrong dynamic field
_ -------------------

mk_enc <<EOF
dynamic idx 0 str value
EOF

tst_encode --expect-error IDX

_ -------------------------
_ Wrong never-indexed field
_ -------------------------

mk_enc <<EOF
never idx 99999 str value
EOF

tst_encode --expect-error IDX

_ -------------------------------------
_ A dynamic field too big for the table
_ -------------------------------------

mk_hex <<EOF
5409 6c6f 6361 6c68 6f73 74             | T.localhost
EOF

mk_msg <<EOF
access-control-allow-origin: localhost
EOF

mk_enc <<EOF
dynamic idx 20 str localhost
EOF

tst_encode --table-size 42

_ ---------------------------------
_ Partial encoding of a header list
_ ---------------------------------


mk_hex <<EOF
0004 6e61 6d65 0576 616c 7565 0005 6f74 | ..name.value..ot
6865 7205 6669 656c 64                  | her.field
EOF

mk_msg <<EOF
name: value
other: field
EOF

mk_enc <<EOF
literal str name str value
push
literal str other str field
send
EOF

tst_encode
