#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2024 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_msg </dev/null
mk_tbl </dev/null

_ ----------------
_ Lost HPACK block
_ ----------------

mk_enc <<EOF
resize 256

# lost OPTIONS request
literal idx 2 str OPTIONS
indexed 6
indexed 4
dynamic idx 1 str www.example.com
dynamic idx 24 str no-cache
dynamic str custom-key str custom-value
drop

# GET request
indexed 2
indexed 6
indexed 4
indexed 64
indexed 63
indexed 62
literal idx 62 str literal-value
dynamic idx 32 str sess_id=123
dynamic idx 32 str user_name=foo
send
EOF

mk_msg <<EOF
:method: GET (+0x0)
:scheme: http (+0x1)
:path: / (+0x2)
<unknown name>: <unknown value> (+0x3)
<unknown name>: <unknown value> (+0x4)
<unknown name>: <unknown value> (+0x5)
<unknown name>: literal-value (+0x6)
cookie: sess_id=123 (+0x16)
cookie: user_name=foo (+0x23)
EOF

mk_tbl <<EOF
[  1] (s =  51) cookie: user_name=foo
[  2] (s =  49) cookie: sess_id=123
      Table size: 100
EOF

tst_monitor
