#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
# Appendix C.3.1.  First Request
8286 8441 0f77 7777 2e65 7861 6d70 6c65 | ...A.www.example
2e63 6f6d                               | .com

# Appendix C.3.2.  Second Request
8286 84be 5808 6e6f 2d63 6163 6865      | ....X.no-cache
EOF

mk_msg <<EOF
# Appendix C.3.1.  First Request
:method: GET
:scheme: http
:path: /
:authority: www.example.com

# Appendix C.3.2.  Second Request
:method: GET
:scheme: http
:path: /
:authority: www.example.com
cache-control: no-cache
EOF

mk_tbl <<EOF
[  1] (s =  53) cache-control: no-cache
[  2] (s =  57) :authority: www.example.com
      Table size: 110
EOF

mk_enc <<EOF
# Appendix C.3.1.  First Request
indexed 2
indexed 6
indexed 4
dynamic idx 1 str www.example.com
send

# Appendix C.3.2.  Second Request
indexed 2
indexed 6
indexed 4
indexed 62
dynamic idx 24 str no-cache
EOF

tst_decode --decoding-spec d20,
tst_encode
