#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
040c 2f73 616d 706c 652f 7061 7468      | ../sample/path
EOF

mk_msg <<EOF
:path: /sample/path
EOF

mk_tbl </dev/null

mk_enc <<EOF
literal idx 4 str /sample/path
EOF

tst_decode
tst_encode
