#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
1008 7061 7373 776f 7264 0673 6563 7265 | ..password.secre
74                                      | t
EOF

mk_msg <<EOF
password: secret
EOF

mk_tbl </dev/null

mk_enc <<EOF
never str password str secret
EOF

tst_decode
tst_encode
