#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
82                                      | .
EOF

mk_msg <<EOF
:method: GET
EOF

mk_tbl </dev/null

mk_enc <<EOF
indexed 2
EOF

tst_decode
tst_encode

# Do the decoding again, with a bindump
mk_bin <<EOF
10000010 | 0x82
EOF

tst_decode
tst_encode
