#!/bin/sh
#
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.
#
# 4.3.  Header Compression and Decompression
#
#    [...]
#
#    A receiving endpoint reassembles the header block by concatenating
#    its fragments and then decompresses the block to reconstruct the
#    header list.
#
#    A complete header block consists of either:
#
#    o  a single HEADERS or PUSH_PROMISE frame, with the END_HEADERS flag
#       set, or
#
#    o  a HEADERS or PUSH_PROMISE frame with the END_HEADERS flag cleared
#       and one or more CONTINUATION frames, where the last CONTINUATION
#       frame has the END_HEADERS flag set.
#
#    [...]

. "$(dirname "$0")"/common.sh

_ ---------------------------------------
_ Decode partial blocks at field boundary
_ ---------------------------------------

mk_hex <<EOF
# C.5.1.  First Response
# first half
4803 3330 3258 0770 7269 7661 7465 611d | H.302X.privatea.
4d6f 6e2c 2032 3120 4f63 7420 3230 3133 | Mon, 21 Oct 2013
2032 303a 3133 3a32 3120 474d 54        |  20:13:21 GMT

# second half
                                6e 1768 |              n.h
7474 7073 3a2f 2f77 7777 2e65 7861 6d70 | ttps://www.examp
6c65 2e63 6f6d                          | le.com
EOF

mk_msg <<EOF
:status: 302
cache-control: private
date: Mon, 21 Oct 2013 20:13:21 GMT
location: https://www.example.com
EOF

mk_tbl </dev/null

tst_decode --decoding-spec p45, --table-size 32

_ -------------------------------------
_ Break inside an indexed field integer
_ -------------------------------------

mk_hex <<EOF
# indexed field 257 (invalid index)
ff81 8000
EOF

HDECODE=hdecode # XXX: nghttp2 1.7.1 fails this test and those below

tst_decode --expect-error IDX

tst_decode --decoding-spec p1, --expect-error IDX
tst_decode --decoding-spec p2, --expect-error IDX
tst_decode --decoding-spec p3, --expect-error IDX
tst_decode --decoding-spec p1,p1, --expect-error IDX
tst_decode --decoding-spec p1,p2, --expect-error IDX
tst_decode --decoding-spec p2,p1, --expect-error IDX
tst_decode --decoding-spec p1,p1,p1, --expect-error IDX

_ -----------------------------------
_ Break inside a table update integer
_ -----------------------------------

mk_hex <<EOF
# table update of 256
3fe1 01                                 | ?..

# C.2.2.  Literal Header Field without Indexing
040c 2f73 616d 706c 652f 7061 7468      | ../sample/path
EOF

mk_msg <<EOF
:path: /sample/path
EOF

tst_decode

tst_decode --decoding-spec p1,
tst_decode --decoding-spec p2,
tst_decode --decoding-spec p1,p1,

_ -------------------------
_ Break inside a field name
_ -------------------------

mk_hex <<EOF
# literal field "long-name-...
007f 0b6c 6f6e 672d 6e61 6d65 2d        | ...long-name-

# ...333333"
$(mk_chars 3 %256s)

# : "value"
0576 616c 7565                          | .value
EOF

mk_msg <<EOF
long-name-$(mk_chars 3 %128s): value
EOF

tst_decode

tst_decode --decoding-spec p2,    # break inside the length
tst_decode --decoding-spec p1,    # break before the length
tst_decode --decoding-spec p1,p1, # break before and inside the length

tst_decode --decoding-spec p3,    # break before the string
tst_decode --decoding-spec p100,  # break inside the string

_ --------------------------
_ Break inside a field value
_ --------------------------

mk_hex <<EOF
# literal field "name: long-value-...
0004 6e61 6d65 7f0c 6c6f 6e67 2d76 616c | ..name..long-val
7565 2d                                 | ue-

# ...333333"
$(mk_chars 3 %256s)
EOF

mk_msg <<EOF
name: long-value-$(mk_chars 3 %128s)
EOF

tst_decode

tst_decode --decoding-spec p7,    # break inside the length
tst_decode --decoding-spec p6,    # break before the length
tst_decode --decoding-spec p6,p1, # break before and inside the length

tst_decode --decoding-spec p8,    # break before the string
tst_decode --decoding-spec p100,  # break inside the string

_ -----------------------------
_ Break inside a Huffman string
_ -----------------------------

mk_hex <<EOF
# literal field "zero: ...
0004 7a65 726f d0                       | ..zero.

# ...000000"
$(mk_chars 0 %160s)
EOF

mk_msg <<EOF
zero: $(mk_chars 0 %128s)
EOF

tst_decode

tst_decode --decoding-spec p7,  # break before the string
tst_decode --decoding-spec p50, # break inside the string
