#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
4803 3330 3258 0770 7269 7661 7465 611d | H.302X.privatea.
4d6f 6e2c 2032 3120 4f63 7420 3230 3133 | Mon, 21 Oct 2013
2032 303a 3133 3a32 3120 474d 546e 1768 |  20:13:21 GMTn.h
7474 7073 3a2f 2f77 7777 2e65 7861 6d70 | ttps://www.examp
6c65 2e63 6f6d                          | le.com
EOF

mk_msg <<EOF
:status: 302
cache-control: private
date: Mon, 21 Oct 2013 20:13:21 GMT
location: https://www.example.com
EOF

mk_tbl <<EOF
[  1] (s =  63) location: https://www.example.com
[  2] (s =  65) date: Mon, 21 Oct 2013 20:13:21 GMT
[  3] (s =  52) cache-control: private
[  4] (s =  42) :status: 302
      Table size: 222
EOF

mk_enc <<EOF
dynamic idx 8 str 302
dynamic idx 24 str private
dynamic idx 33 str Mon, 21 Oct 2013 20:13:21 GMT
dynamic idx 46 str https://www.example.com
EOF

tst_decode --table-size 256
tst_encode --table-size 256
