#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
8286 8441 8cf1 e3c2 e5f2 3a6b a0ab 90f4 | ...A......:k....
ff                                      | .
EOF

mk_msg <<EOF
:method: GET
:scheme: http
:path: /
:authority: www.example.com
EOF

mk_tbl <<EOF
[  1] (s =  57) :authority: www.example.com
      Table size:  57
EOF

mk_enc <<EOF
indexed 2
indexed 6
indexed 4
dynamic idx 1 huf www.example.com
EOF

tst_decode
tst_encode
