#!/bin/sh
#
# License: BSD-2-Clause
# (c) 2016 Dridi Boukelmoune <dridi.boukelmoune@gmail.com>

. "$(dirname "$0")"/common.sh

mk_hex <<EOF
400a 6375 7374 6f6d 2d6b 6579 0d63 7573 | @.custom-key.cus
746f 6d2d 6865 6164 6572                | tom-header
EOF

mk_msg <<EOF
custom-key: custom-header
EOF

mk_tbl <<EOF
[  1] (s =  55) custom-key: custom-header
      Table size:  55
EOF

mk_enc <<EOF
dynamic str custom-key str custom-header
EOF

tst_decode
tst_encode
